### ISSUE TITLE
model quality?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/mfbdjvu#4]
Hi @plzombie .

New model BG/FG quality.

Old [0,100] {default = 75}:
https://github.com/ImageProcessing-ElectronicPublications/mfbdjvu/blob/fb7f45638088a2a239f2066bd82a42100698fb5b/src/mfbdjvu.cpp#L155-L163

New [0,Inf] {default = 100};
```c
                n = (n < 0) ? 0 : n;
                keys->quality = sqrt(n) * 0.1f;
                vector<int> nf, nb;
                nb.push_back((int)(keys->quality * 76.0f + 0.5f) + 5);
                nb.push_back((int)(keys->quality * 84.0f + 0.5f) + 5);
                nb.push_back((int)(keys->quality * 95.0f + 0.5f) + 5);
                keys->slices_bg = nb;
                nf.push_back((int)(keys->quality * 95.0f + 0.5f) + 5);
                keys->slices_fg = nf;
```

:warning: Both models are non-linear (`sqrt`)!

PS: I don't like the upper limit of the old model.

**Comment by plzombie** [comment]
-slice 100 is like jpeg 70-90%.  -slice 130 is close to lossless when transcoding from jpeg. With default djvulibre coefficients jpeg images I tested may look blurry. So I don't know that coefficients will be better

**Comment by zvezdochiot** [comment]
@plzombie say:
>-slice 100 is like jpeg 70-90%

А вот здесь ты не путай. В PDF-как JPEG в районе `-quality 50` и ниже при DPI 150. Надо понимать, что из-за DPI в типографии "немного" иная шкала качества.

**Comment by zvezdochiot** [comment]
Hi @plzombie .

Я тут заметил, что ежели использовать логарифмическую модель:
```c
                n = (n < 0) ? 0 : n;
                keys->quality = (float)n;
                float lq = log10(1.0f + keys->quality * 0.09f);
                vector<int> nf, nb;
                nb.push_back((int)(lq * 76.0f + 0.5f) + 5);
                nb.push_back((int)(lq * 84.0f + 0.5f) + 5);
                nb.push_back((int)(lq * 95.0f + 0.5f) + 5);
                keys->slices_bg = nb;
                nf.push_back((int)(lq * 95.0f + 0.5f) + 5);
                keys->slices_fg = nf;
```
то качество, которое "хочешь" ты будет соответствовать `-quality 200`. Интересное кино. Никаких не 130 или другой непонятной цифири. В совпадения не верю ни разу.

**Comment by plzombie** [comment]
Я сохранял со своей. Скорее всего, твоя степенная функция будет равномернее качество давать, потому что после 50 там менее явные изменения (если не сравнивать пиксель-в-пиксель)
На счёт, почему 100 соответствует -slice 130, вот например скан манускрипта войнича
![изображение](https://user-images.githubusercontent.com/1690651/213865576-878dc65f-0079-4819-8aec-6851e3573380.png)
Видно что c44 слишком сильно пережимает chroma. Хотя в настройках по умолчанию там должно быть всё норм.
Плюс я с этой же метрикой хочу сохранять фотоальбомы, например. И там уже картинка выглядит мыльной со -slice 100

**Comment by zvezdochiot** [comment]
@plzombie say:
>Плюс я с этой же метрикой хочу сохранять фотоальбомы

Слегка перебор. Дефолтное качество не для фоток. Для фоток качество должно быть явно выше дефолтного. И в этом плане твоё искусственное ограничение шкалы quality сверху мне совсем не нравится. Ничуть не меньше, чем линейность самой твоей шкалы. Что мешает для фоток устанавливать `-quality 200`?

**Comment by plzombie** [comment]
Я -quality 100 рассматриваю не как дефолтное значение, а как "отличное" качество. А по умолчанию можно и -quality 75 сделать. -bgs 3 -fgs 2 же тоже совершенно не подходит для -dpi 200 например

> Ну как сказать. Картинка в 600 DPI сжимается гораздо хуже, чем картинка в 100 DPI, но выглядит гораздо лучше. :)

Это уже скорее особенности c44/cjb2. Ну и если изображение сначала сделать чб потом даунскейлить в 6 раз, естественно результат будет лучше, чем если наоборот

**Comment by zvezdochiot** [comment]
@plzombie say:
>А по умолчанию можно и -quality 75

Так и стоит.

@plzombie say:
>не подходит для -dpi 200 например

Где то в описании DjVu жирными буквами написано **"не менее 300"**.

Так всё-таки, что делать со шкалой? Ты меня ни рази не убедил. Исскуственность 130 глаза режет. Предлагаю ещё раз пользовать нелинейную шкалу (sqrt, log10) с 100 в качестве дефолта (ака как у всех), а к всем "особо ценным" материалам применять значения более 100 или пресеты.

**Comment by zvezdochiot** [comment]
@plzombie say:
>Плюс я с этой же метрикой хочу сохранять фотоальбомы

Я бы не советовал сегментацию и IW4 (downsample) для фоток. DjVu позволяет использовать JPG в качестве цветной компоненты. Подробности смотри в [djvujpgpack](https://github.com/BASH-Auto-Tools/djvujpgpack) (режим lossless). Плюс к этому фотоальбомы я лично клепаю либо в [jpeg2pdf](https://github.com/ImageProcessing-ElectronicPublications/jpeg2pdf), либо 7z: ZIP image + description.txt rename to CBZ.

**Comment by plzombie** [comment]
Сегментацию для фоток, понятное дело, не имеет смысла. 
Я всё-таки расцениваю quality как процент от 0 до 100, где ниже-выше в большинстве случаев не имеет смысла. А у тебя получается со 100% будет размываться цветность, какие-нибудь книги с иллюстрациями или комиксы придётся всё равно с 200 кодировать. Если логарифмическую функцию использовать.

**Comment by zvezdochiot** [comment]
@plzombie say:
> расцениваю quality как процент от 0 до 100

Процент от чего? От 130? А 130 - это что? Вот хде вопрос.

Потестил я шкалку, а заодно поковырял свои djvu-шки и пришёл к следущим выводам:
* "ноль" в твоей модели выбран неверный, он не "5", а "20".
* BG в большинсте книг 4х-компонентный.

Следовательно:
```c
                n = (n < 0) ? 0 : n;
                keys->quality = (float)n;
                float lq = log10(1.0f + keys->quality * 0.09f);
                vector<int> nf, nb;
                nb.push_back((int)(lq * 60.0f + 0.5f) + 17);
                nb.push_back((int)(lq * 69.0f + 0.5f) + 18);
                nb.push_back((int)(lq * 72.0f + 0.5f) + 19);
                nb.push_back((int)(lq * 80.0f + 0.5f) + 20);
                keys->slices_bg = nb;
                nf.push_back((int)(lq * 80.0f + 0.5f) + 20);
                keys->slices_fg = nf;
```
* quality = 0, slices fg = 20, slices bg = {17,18,19,20}
* quality = 50, slices fg = 79, slices bg = {61,69,72,79}
* quality = 100, slices fg = 100, slices bg = {77,87,91,100}
* quality = 200, slices fg = 122, slices bg = {94,106,111,122}

**Comment by zvezdochiot** [comment]
@plzombie . Надо к чему то приходить. Меня категорически не устраивает твоя шкала. Тебя чем то не устраивает моя. Предлагай тогда хоть что то более вменяемое. Будем посмотреть. Но так как щаз оставлять точно не следует.

**Comment by plzombie** [comment]
Что ты подразумеваешь под "как у всех"? Если стандартные параметры в djvulibre, то у меня это -quality 69

**Comment by zvezdochiot** [comment]
@plzombie say:
>Что ты подразумеваешь под "как у всех"?

@zvezdochiot say:
>slices fg = 100, slices bg = {74,84,88,97} ("как у всех")

**Comment by plzombie** [comment]
Это djvu solo такие параметры выдаёт?
Не знаю, чем тебе не нравится линейная шкала. У тебя при quality > 60 значения топчутся на месте с степенной функцией

**Comment by zvezdochiot** [comment]
@plzombie say:
>Это djvu solo такие параметры выдаёт?

Нет. DjVuSolo не умеет FG44.

@plzombie say:
>Не знаю, чем тебе не нравится линейная шкала.

@zvezdochiot say:
>Сохрани в ряд -quality = 0, 25, 50, 75, 100, и визуально оцени.

"Это" категорически не нравится моим глазам. И мне не нравится искусственный верхний предел.

@plzombie say:
>И мне кажется tiff сейчас такая же экзотика, как и netpbm.

Уверен? Только вот именно он является частью PDF: CCITT Fax Group{3,4}, JBIG2.

**Comment by plzombie** [comment]
> "Это" категорически не нравится моим глазам. И мне не нравится искусственный верхний предел.
По мне, там явно есть прогресс между 0, 15, 25, 40, 50, 60, 70...

> Уверен? Только вот именно он является частью PDF: CCITT Fax Group{3,4}, JBIG2.
Ну ок. То что в tiff запихнули zip(deflate), jpeg и jbig не отменяет того факта, что люди предпочитают png(deflate), jpeg и... где там используется jbig

**Comment by plzombie** [comment]
> По мне, там явно есть прогресс между 0, 15, 25, 40, 50, 60, 70...
Ну можно для quality < 70 как раз использовать степенную функцию. Но выше -slices 130 я не вижу смысла делать. И никто тебя не заставляет у себя в программе делать верхний предел

**Comment by zvezdochiot** [comment]
@plzombie say:
>По мне, там...

Что у тебя со знением? Или самовнущение. Тогда сравни с [mfbdjvu](https://github.com/ImageProcessing-ElectronicPublications/mfbdjvu) в нынешнем состоянии шкалы.

@plzombie say:
>люди предпочитают png(deflate)

**Мне ненужен png(deflate)! Он не подходит для MFB!** Мне нужен CCITT Fax Group4, JBIG2.

**Comment by plzombie** [comment]
![изображение](https://user-images.githubusercontent.com/1690651/213934295-37e2fc07-122e-44dc-98a0-abe51e239faa.png)
![изображение](https://user-images.githubusercontent.com/1690651/213934438-402f3e1a-cd5d-4b10-8239-3780a8ebf8ef.png)
Ну и если приблизитьт 1:1, то разница между 50/60/70 будет конечно же больше

> Мне ненужен png(deflate)! Он не подходит для MFB! Мне нужен CCITT Fax Group4, JBIG2. (И кстати, в PDF нифига не PNG, а его извращённая страшным образом производная).

Ты хочешь из tiff напрямую в djvu передавать jb2? Без перекодирования?

**Comment by zvezdochiot** [comment]
@plzombie say:
>то разница

Всё познаётся в сравнении:
>Тогда сравни с [mfbdjvu](https://github.com/ImageProcessing-ElectronicPublications/mfbdjvu) в нынешнем состоянии шкалы.

@plzombie say:
>Ты хочешь из tiff напрямую в djvu передавать jb2? Без перекодирования?

Вообще то разговор был за PDF. Ежели вернуть всё на места, то да. Tiff и JPEG встраиваются в PDF без перекодирования (в отличии от PNG).

**Comment by plzombie** [comment]
png - lossless. Все lossy алгоритмы для png основываются на том, что ты сначала применяешь квантование/постеризацию

**Comment by zvezdochiot** [comment]
@plzombie say:
>png - lossless.

Tiff тоже по болшей части lossless. И?

**Comment by zvezdochiot** [comment]
Hi @plzombie .

Тестирование [последней версии log_quality](https://github.com/ImageProcessing-ElectronicPublications/mfbdjvu/issues/4#issuecomment-1399283135):
![mona series](https://user-images.githubusercontent.com/12370082/214055540-b4669ae6-ea34-4c05-880a-daf95cb3d365.jpg)
слева-направо, сверху-вниз: origin, quality 0, 5, 10,. .., 145, 150.

Представление метриками:
![m](https://user-images.githubusercontent.com/12370082/214055883-00ccea08-4b8d-40fa-b5a4-af0f44554425.svg)

Согласно более направленной на человеческое восприятие VIFP1 шкала очень даже лаконично. Но! Она же позволяет назначить дефолтное значение 75 вместо 100 (см. график)

Логарифмическая шкала с дефолтом в 75:
```c
                n = (n < 0) ? 0 : n;
                keys->quality = (float)n * 0.01f;
                float lq = log10(1.0f + keys->quality * 12.0f);
                vector<int> nf, nb;
                nb.push_back((int)(lq * 57.0f + 0.5f) + 17);
                nb.push_back((int)(lq * 66.0f + 0.5f) + 18);
                nb.push_back((int)(lq * 69.0f + 0.5f) + 19);
                nb.push_back((int)(lq * 77.0f + 0.5f) + 20);
                keys->slices_bg = nb;
                nf.push_back((int)(lq * 80.0f + 0.5f) + 20);
                keys->slices_fg = nf;
```
* quality = 25, slices fg = 68, slices bg = {51,58,61,66}
* quality = 50, slices fg = 88, slices bg = {65,74,77,85}
* quality = 75, slices fg = 100, slices bg = {74,84,88,97} ("как у всех")
* quality = 100, slices fg = 109, slices bg = {80,92,96,106}

**Comment by plzombie** [comment]
Я визуально их почти не отличаю с конца второго ряда. Могу, допустим, в свою программу добавить выбор метрики для quality

**Comment by plzombie** [comment]
67-70 примерный аналог твоего 75

**Comment by zvezdochiot** [comment]
@plzombie say:
>67-70

Всё гуд. Сборочку сделаешь?

**Comment by plzombie** [comment]
Ок, сейчас

**Comment by plzombie** [comment]
@zvezdochiot Посмотри здесь варнинги, связанные с неявным приведением типов https://github.com/plzombie/depress/commit/05c6d459498023bac902f966961aaaa1f1946868

Строки 351,359,613,621 - не совсем понятно, зачем ты к float приводишь, если обе переменные - int, и результат будет приведён к int

**Comment by zvezdochiot** [comment]
@plzombie say:
>Строки 351,359,613,621 

https://github.com/plzombie/depress/blob/05c6d459498023bac902f966961aaaa1f1946868/src/third_party/djvul.h#L84
Твою ж мать. А ведь накопители должны быть в `float` (оберег для больших изображений). И ведь делал же вроде. Ну как так то?

**Comment by zvezdochiot** [comment]
Hi @plzombie .

* [DjVuScan-Forum: MFBdjvu](http://www.djvu-scan.ru/forum/index.php?topic=49329.0)
* [DjVuScan-Forum: MFBpdf](http://www.djvu-scan.ru/forum/index.php?topic=49330.0)

**Comment by zvezdochiot** [comment]
Hi @plzombie .
[OCR форумы](http://publ.lib.ru/cgi/forum/YaBB.pl):
* [OCR форумы: MFBdjvu](http://publ.lib.ru/cgi/forum/YaBB.pl?num=1674762466)
* [OCR форумы: MFBpdf](http://publ.lib.ru/cgi/forum/YaBB.pl?num=1674762649)

**Comment by zvezdochiot** [comment]
Привет @plzombie .

Сделаешь, как будет время, сборку https://github.com/ImageProcessing-ElectronicPublications/mfbdjvu/releases/tag/2.1 ? А то на [ru-board](http://forum.ru-board.com/topic.cgi?forum=5&topic=51044&start=120#16) смог сослаться только на 2.0.

**Comment by plzombie** [comment]
@zvezdochiot 
Готово

**Comment by zvezdochiot** [comment]
@plzombie 
Огромное сенкс.
Только наверное (я не уверен) надо `win32` на `win` заменить в названиях архивов. Но я хз, может всё и верно.
:+1:
